
~/.bash_profile
export PROMPT_COMMAND="pwd > /tmp/whereami"
export QSYS_ROOTDIR="/home/chris/.cache/yay/quartus-free/pkg/quartus-free/opt/altera/19.1/quartus/sopc_builder/bin"
source /home/chris/.bazel/bin/bazel-complete.bash
export PS1="[\[$(tput sgr0)\]\[\033[38;5;85m\]\h\[$(tput sgr0)\]\[\033[38;5;15m\]@\[$(tput sgr0)\]\[\033[38;5;82m\]\u\[$(tput sgr0)\]\[\033[38;5;211m\] \w]\[\033[38;5;15m\]\\$ \[\033[38;5;83m\]\@\n>>> \[$(tput sgr0)\]"
