
~/.bash_profile
export PROMPT_COMMAND="pwd > /tmp/whereami"
source /home/chris/.bazel/bin/bazel-complete.bash
export PS1="[\[$(tput sgr0)\]\[\033[38;5;85m\]\h\[$(tput sgr0)\]\[\033[38;5;15m\]@\[$(tput sgr0)\]\[\033[38;5;82m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\] \w]\\$ \@\n>>> \[$(tput sgr0)\]"
